### ISSUE TITLE
Challege React 18 (PropTypes)

### ISSUE THREAD

**Issue by dgrcode** [bonham000/fcc-react-tests-module#118]
There are two things that I would like to discuss about this challenge.

1. It makes a reference to the documentation, but it is not linked. I think a link there could help some people find the documentation in an easy way. I don't know if that was done like this on purpose to push people to get used to find documentation on their own, so I wanted to open the discussion.

2. There is an example where it is shown how to use `PropTypes` to make a specific property receive a function **and** to be required. Then, the instructions asks to define a `PropType` to check that a prop called "quantity" is of type number, **but it doesn't say anything about being required**. It is neither requested on the tests summary that turns green when the tests are passed. If you define quantity to be of type number it will not pass the tests until the `.isRequired` is added. I would suggest to modify the instructions to ask explicitly for the "quantity" property to be required, and update the test comments accordingly

I am open to create a PR if that would help, although I am a bit scared about breaking something. I'm quite new to contributing to repositories that I don't own

**Comment by dgrcode** [comment]
Same as point 2 found at challenge React 20. It says:

> Finally, define `propTypes` on the `Camper` component that require the `name` to be a `string`.

I understand it as the `name` **is required to be** a `string`, but not that it **is required to be specified** for the `Camper` component.

**Comment by HKuz** [comment]
@dgrcode these are good points. @bonham000 - I think in my attempts to simplify some of the instructions, the specificity got lost. I believe Challenge 18 (Use PropTypes to Define the Props You Expect) is the first time the `isRequired` method comes up - I think it would be helpful to add a blurb explaining that it requires the prop to be provided. The way the challenge is currently written, it seems like the `isRequired` part in the example is requiring that prop X be of type Y. Maybe we add a new paragraph right after the `MyComponent` example that reads something like: 

"In the example above, the <code>React.PropTypes.func</code> part checks that <code>handleClick</code> is a function. The <code>isRequired</code> method tells React that the <code>handleClick</code> is a required property for that component. You will see a warning if that prop isn't provided." (continue with the next paragraph "Notice that `func`...")

New challenge 18 instructions: Define <code>propTypes</code> for the <code>Items</code> component to check that the <code>quantity</code> prop is of type <code>number</code>. Also, require that the <code>Items</code> component has a <code>quantity</code> prop.

For challenge 20, we can clarify the last sentence of the instructions: Finally, define <code>propTypes</code> on the <code>Camper</code> component, so that the <code>name</code> property is required, and it is of type <code>string</code>.

(Feel free to re-word this in another way - these are just suggestions).

As for links - so these challenges will be ported over to the FCC site as part of the curriculum expansion. The current thinking for new challenges is to try to limit any external links - those will go in the corresponding wiki articles. The idea is to try to keep campers moving through the challenges, and not have to break their flow to go look something up/check out another web page. @bonham000 - up to you if you want to include a link here 😄 

@bonham000 - I'm happy to make any changes if you're on board with these suggestions. I'm working on a PR for the advanced rendering section of the React challenges right now. That said, text changes I'm fine making, but I'd need some help if you want to change the tests.

**Comment by bonham000** [comment]
Ok, great points to bring up @dgrcode! Thanks for pointing this out. Because I was looking closely at both of these challenges to understand the concerns here I went ahead and revised them both to hopefully fix the problem. Also, @HKuz's comments about external links is the reason why there isn't a link here, so for the time being I will continue to leave links out.
