### ISSUE TITLE
Challenge React 26. Bind "this" with Arrow Functions

### ISSUE THREAD

**Issue by dgrcode** [bonham000/fcc-react-tests-module#123]
When solving this challenge I used different codes for the arrow functions that were not valid, even though the component was working as expected. The test that was not passed said: 

> The setMessage method should be defined with a fat arrow function.

Here are the code that **didn't pass** that test, but were working:

- `setMessage = args => this.setState({message: "Goodbye!"});`
- `setMessage = (args) => this.setState({message: "Goodbye!"});`
- `setMessage = (x, y) => this.setState({message: "Goodbye!"});`

And the only solution that **passed** the test was:

- `setMessage = () => this.setState({message: "Goodbye!"});`

Probably the three ways of writing the function that didn't pass are not compliant with good practices, given that I'm defining an argument where no argument is actually expected. However, those are valid ways to writing the arrow function and the React component is actually working with all of them.

What do you think, should those solutions be considered valid or not?

**Comment by bonham000** [comment]
Because of the way we're testing the arrow function writing the function with argument(s) will fail the tests, even though those are valid arrow functions... There is no need to write the function with any arguments here, however, you could do so and then pass in `Goodbye` as an argument from where the function is called and then set that as the value of `message`. Because someone might try to do this just to experiment, I'll make a note in the challenge that to pass the tests the arrow function must be written without any arguments.
