### ISSUE TITLE
React 02: Create a Complex JSX Element - Lacks Explanation of 'const'

### ISSUE THREAD

**Issue by JessiW** [bonham000/fcc-react-tests-module#161]
In this challenge, I noticed that students are directed to create a new 'constant' without any mention of what 'const' actually is and what it means.  A brief explanation of const - explaining its like the ES6 version of a variable - would be helpful to those who aren't familiar. I'm sure you cover ES6 further on in this curriculum - but until then, the user might not necessarily know what 'const' (constant) means.

Hope that makes sense!

- Jessi

**Comment by bonham000** [comment]
We do, and in the final updated version of the upcoming curriculum, there will be specific challenges in the JavaScript section that present ES6 features such as `const`. Because of this, and because one of FCC's goals with the challenges is to minimize links to external resources we probably won't include a link here to this.
