### ISSUE TITLE
React 47: Use Array.map() to Dynamically Render Elements

### ISSUE THREAD

**Issue by piotr-m-jurek** [bonham000/fcc-react-tests-module#175]
Hi,
there is something wrong with this challange. I did it and tried to test by writing : 'eat, code, sleep, repeat'
and it refreshed the component while I was writing it. At first i thought it was something with my solution, but the same situation repeated on `Solution Code`. I tested it on Firefox and Chrome, thinking it might be cross browser problem, but it keeps refreshing before clicking `Create List` button.
Anyone has same problems with it?

**Comment by bonham000** [comment]
Hi @piotr-m-jurek, I've just tested this challenge based on what you said and I didn't see any problems.

Loading the solution code and typing `eat, sleep, code, repeat` into the input box and clicking the `Create List` button rendered those words as `li` items in a list.

One thing to note is that we have set up specific key combinations that can trigger the page to load the seed or solution code. These are `Shift + S` for solution code and `Shift + R` for seed code. If you pushed one of those key combinations anywhere in your process, it could create the behavior you are seeing. Otherwise, if you are still experiencing the same problem please try to reply with more description about what is happening.

**Comment by piotr-m-jurek** [comment]
Oh man, I feel so stupid now...
I wasn't aware of the `Ctrl+S` and `Ctrl+R` key combinations  (maybe it should be specified on the button, with small font below or sth ?). 
The instruction is a bit missleading : _Try entering the string `Eat, Code, Sleep, Repeat` into the textarea, [...]_  and wile writing `Sleep` it loaded solution code - restarted the state (and I haven't noticed it). 

Maybe we should change capital letters in the instructions no to misguide future challengees.

**Comment by bonham000** [comment]
Yeah, no worries! I just updated the example code to be lowercase that's definitely a good suggestion. We mainly had these shortcut keys for when we were developing the project and since these won't exist in the FCC platform I probably won't mention them in the project itself.
