### ISSUE TITLE
React 36 - using arrow functions does not pass the tests

### ISSUE THREAD

**Issue by zelite** [bonham000/fcc-react-tests-module#177]
On the challenge: Manage Updates with Lifecycle Methods.

I made the following methods:

```
  componentWillReceiveProps = (nextProps) => {
  	console.log(this.props);
        console.log(nextProps);
  }
  componentDidUpdate = () => {
  	console.log("The component has updated");
  }
```

And the last three tests fail. I can see the messages being logged in the console. 
If I change the functions to use the usual method notation instead of arrow functions, the tests pass. Is this how it's supposed to work. What's the difference from using an arrow function and the regular method in this context? I assume the "this" is pointing at the right place, because the console.log(this.props) works as expected.

**Comment by bonham000** [comment]
Yeah, interesting. I'm not sure why arrow functions would not be working for this. I'm going to continue looking into it, worst case is we can just add a note in the instructions which says you need to define your methods normally in order for the tests to work.

**Comment by no-stack-dub-sack** [comment]
@bonham000 this is interesting because it goes back to our conversation the other day, about how when I was building an app, I had to use a babel-preset in order to write React methods with the arrow syntax. I still don't fully understand why it doesn't work, but this is the article I found that supports there's an extra step needed to make this ok: https://medium.com/@machnicki/handle-events-in-react-with-arrow-functions-ede88184bbb#.y8decr5xu

I guess this would be different though because these are built in lifecycle hooks... so that's even stranger. But I guess my main point is, for some reason, compilers don't like arrow syntax for methods on React components

But also, it looks like the messages are being logged, so its not like its not working. I'm going to play around it and see.

**Comment by no-stack-dub-sack** [comment]
@zelite Also, it's worth noting, that there really is no need to ever write lifecycle methods using this syntax. These are built-in methods and the binding of `this` is done behind the scenes to assure you never need to do things like this, or bother with binding them in the constructor. So basically, you're just adding extra keystrokes and a bulkier syntax to your code unnecessarily

**Comment by bonham000** [comment]
I'm going to make a note on this to not use arrow functions for lifecycle methods. This is due in some way to how we are testing and how Babel is transpiling arrow functions as class methods.
