### ISSUE TITLE
React 44 - Alternative solution not validated?

### ISSUE THREAD

**Issue by dloret** [bonham000/fcc-react-tests-module#179]
Hello guys, first of all I take this occasion to tell you that I just love what FCC is doing. I learn a lot thanks to you.
In the React 44 challenge, I came up with a working solution expressed a little differently
`(!this.state.userAge) ? buttonOne : (this.state.userAge < 18) ? buttonThree  : buttonTwo;`

I hope I'm not wasting your time opening this issue, but with this solution the following test is not validated:
> When a number of less than 18 is entered into the input element and the button is clicked, the button's inner text should read "You Shall Not Pass".

But when I input 17 in the field, I get "You Shall Not Pass". Then, 18 returns "You May Enter"
Perhaps my solution is not so clear as the one proposed, but shouldn't it pass? If not may I ask why, just to understand?

Thanks a lot for your time.

**Comment by bonham000** [comment]
Actually, your solution is 100% correct and I'm glad you brought this up! That failing test for your solution is because `0` is falsy in JavaScript and part of that test was setting the input to `0` which caused your solution to fail because the first condition would then be true and `buttonOne` would be rendered (rather than the expected `buttonThree`. I changed the test so it's not trying to test `0` and your solution should pass now.
