### ISSUE TITLE
Questions about Challenge-React 49

### ISSUE THREAD

**Issue by ccrubby214** [bonham000/fcc-react-tests-module#203]
hi @bonham000 ,  I have finished the part of React Challenge, and when I worked in the challenge-React 49, I found something in `Solution Code` I couldn't understand as below:

`const usersOnline = this.state.users.filter((user) => {
  		return user.online;
  	});`
`const renderOnlineUsers = usersOnline.map((user) => {
  		return (
  			<li>{user.username}</li>
  		);
  	});`

1. in the ```usersOnline```，how to filter the array of `this.state.users`  get through `return user.online` , not `return user.online === true`?  I had read the filter funtion definition from Mozilla [Array.prototype.filter()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter). But I still not clear about the usage here.

2. in the ```renderOnlineUsers```, you said in the last challenge, we need to markup a unique key attribute in the map's argument when there is an array of elements, but here is no one, so I want to know is it still ok?

**Comment by bonham000** [comment]
Hi @ccrubby214 

1. It's because in this example the `online` property in `user` is a boolean, so simply writing `user.online` should evaluate to `true` (then we want to display the user) or `false` (then we want to filter the user out. Does that make sense? It's really just concise syntax for this:

``` javascript
const usersOnline = this.state.users.filter(function(user) {
   return user.Online === true;
});
```

2. You are totally correct about the missing key attribute. Those got added after the initial draft of these challenges and we clearly overlooked this challenge. I'll go in an try to add it now. Thank you!

Let me know if you have any other questions. In the meantime I'll close this issue.
