### ISSUE TITLE
Challenge 4 : Live Preview does not work

### ISSUE THREAD

**Issue by alayek** [bonham000/fcc-react-tests-module#22]
In **Challenge 4 : Challenge: Render HTML Elements to the DOM**, the rendering works both with `querySelector` and `getElementById`.

However, the live preview is not getting updated. As in, it's not rendering to any visible node. Do we want to display the output here, to give a quick feedback to campers that `ReactDOM.render()` actually renders?

Tested on Latest chrome on Windows.

**Comment by ghost** [comment]
Same for latest Chrome on OSX. This seems like a really important feature, and will probably help a lot of campers begin to understand the significance of React.

**Comment by bonham000** [comment]
Yes so at the moment the purely JSX challenges do not have a live preview feature even though the box is there on the screen, but there are only a few of these. Whereas almost all of the React challenges have a preview. I agree this feature is very important to have. Because this prototype app will not be how campers actually experience these challenges, I'm not worried about adding a preview for the JSX components at this point. If we feel like it's needed once this is integrated with the FCC platform we can certainly move to add it.

**Comment by ghost** [comment]
Awesome, I figured a live preview would show up eventually, just making sure!

**Comment by bonham000** [comment]
Yes it looks like it appears as soon as React 8.

**Comment by bonham000** [comment]
Also just to note about later challenges, Redux and React Redux, some of these have a 'console.log' preview which is definitely hacked and so while you *can* log to the `console` it is not perfect. But again, that functionality will be provided in a better way by the FCC platform in the end.

**Comment by alayek** [comment]
@bonham000 agreed. Berkeley has the live preview hooked up in the main site which is more battle tested.

Closing in favor of that.
