### ISSUE TITLE
React 23 : Challenge Implementing strict string match. Should probably watch the output instead!

### ISSUE THREAD

**Issue by nzineer** [bonham000/fcc-react-tests-module#243]
React Challenge 23:
```
class MyComponent extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			name: 'Free Code Camp'
		}
	}
	render() {
		// change code below this line
		const name = this.state.name;
	  // change code above this line
  	return (
	    <div>
	    	{ /* change code below this line */ }
	<h1>
                {name}
        </h1>
	    	{ /* change code above this line */ }
	    </div>
    );
  }
};
```
This code does not work and gives and error as follows:
**The rendered h1 tag should include a reference to {name}.**

But when the indentation of the code is changed to a one liner:
i.e from:
```
<h1>
                {name}
        </h1>
```
to
```
<h1>{name}</h1>
```

Then the test cases are all verified. I think it should not be behaving like this and should render in both scenarios.

**Comment by bonham000** [comment]
Hmm interesting discovery @AdityaOli. The test for this case is:

`assert.strictEqual(modifiedCode.includes('<h1>{name}</h1>'), true, error_3);`

which presumably fails because there are new line / whitespace characters in the `h1` tag. I think we could update the test to find the `h1` element and verify that it's child includes `"Free Code Camp"`, and separately verify that the code includes the string `{name}`. This would still not be a perfect solution, but with many of these challenges the tests cases are not unbreakable but about as good as we can get it. Let me know if you're interested in trying to PR a solution for this, otherwise I will do it later when I have a chance! Thanks.

**Comment by bonham000** [comment]
Cool I fixed it.

**Comment by nzineer** [comment]
Could not find a window to work on it! :disappointed: . Thanks @bonham000
