### ISSUE TITLE
Challenge 13: Passes w/o constructor call

### ISSUE THREAD

**Issue by CodeFay** [bonham000/fcc-react-tests-module#75]
Issue: Challenge specifies to "don't forget to call your component's constructor" but am able to pass tests without  including constructor:

Recommendation: Should a test be added to test for the constructor?

Details:

**Sample code that passes**
```
class MyComponent extends React.Component {
	//constructor(props) {
   // super(props);
  //}
  render() {
  return (
    <div>
      <h1>My First React Component!</h1>
      </div>
    );
  }
}
ReactDOM.render(<MyComponent />, document.getElementById('challenge-node'));
```

**Comment by bonham000** [comment]
So it is not actually required in any way to initialize a React class with a constructor and the only way I know to test for this would be to just manually test for the presence of `constructor` as a string within the user's code. The React component will still render without a constructor being called. However Facebook recommends also initializing components with a constructor call so that is why we include that recommendation here.
